### ISSUE TITLE
unit_of_measurement

### ISSUE THREAD

**Issue by megapeer** [djansen1987/SAJeSolar#8]
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:151
Integration: Sensor (documentation, issues)
First occurred: 21:58:16 (15 occurrences)
Last logged: 21:58:19

custom_components.saj_esolar.sensor is setting 'unit_of_measurement' on an instance of SensorEntityDescription, this is not valid and will be unsupported from Home Assistant 2021.11. Please report it to the custom component author.

**Comment by djansen1987** [comment]
Thanks for reporting! Appreciated. Will need some time for this as it will resolve in a lot of programming and again restructuring of the component (again).

**Comment by djansen1987** [comment]
Should be fixed in [v1.2.4](https://github.com/djansen1987/SAJeSolar/releases/tag/v1.2.4). Please see release notes for details.
Please let me know if this solves the Issue.

**Comment by djansen1987** [comment]
Fixed with above solutions

**Comment by bertdebondt** [comment]
bug "custom_components.saj_esolar.sensor is setting 'unit_of_measurement' on an instance of SensorEntityDescription, this is not valid and will be unsupported from Home Assistant 2021.11. Please report it to the custom component author." is reappearing in my log file.

**Comment by djansen1987** [comment]
Hi @8OND007, which version of saj_esolar are you running. This should be fixed in a couple of version back.

**Comment by 8OND007** [comment]
Version 1.2.4 according to the manifest.json file.

Strange HACS did not see 2 updates 1.2.5 and 1.2.6.
I just used the "Redownload" function in HACS so I though I would have 1.2.6.
I restarted HA with the new 1.2.6 but in log I still see : "custom_components.saj_esolar.sensor is setting 'unit_of_measurement' on an instance of SensorEntityDescription, this is not valid and will be unsupported from Home Assistant 2021.11. Please report it to the custom component author."
Again checked manifest.json, and it is still 1.2.4.
Maybe something is wrong with the update version push ?

**Comment by 8OND007** [comment]
the actual manifest.json file on github is still on 1.2.4.
This is probably the cause my HACS does not see a newer update ?

**Comment by djansen1987** [comment]
Hi, i updated the manifest.json, could you check again

**Comment by djansen1987** [comment]
Continue issue in https://github.com/djansen1987/SAJeSolar/issues/19
